import type { FileMap } from "~/lib/stores/files";

export interface WPThemeOptions {
  themeName: string;
  author?: string;
  description?: string;
  version?: string;
}

/**
 * WPThemeBuilder converts an in-memory Starsky project (FileMap) into a WordPress
 * theme folder structure.  The implementation is pragmatic – it grabs the first
 * HTML file it can find, splits out <head> and <body>, copies CSS/JS/assets,
 * and stitches the pieces together into header.php, footer.php, index.php and
 * style.css.  It purposely avoids deep parsing to keep the export fast and
 * resilient; users can refine the theme further once installed in WordPress.
 */
export class WPThemeBuilder {
  async buildTheme(files: FileMap, opts: WPThemeOptions): Promise<Record<string, string>> {
    const theme: Record<string, string> = {};

    // 1. locate main HTML file – prefer index.html, else first *.html we see
    const htmlPath = Object.keys(files).find((p) => p.endsWith("index.html")) ??
      Object.keys(files).find((p) => p.endsWith(".html"));

    const htmlContent = htmlPath && files[htmlPath] && files[htmlPath]!.type === "file"
      ? (files[htmlPath] as any).content as string
      : "";

    const { head, body } = this.splitHtml(htmlContent);

    // 2. Track first CSS and JS files for dynamic enqueuing
    let firstCss = '';
    let firstJs = '';

    // 3. copy CSS/JS/assets into assets/… and track first files
    for (const [path, dirent] of Object.entries(files)) {
      if (!dirent || dirent.type !== "file") continue;
      const rel = path.replace(/^\/*/, ""); // trim leading slash
      if (rel === htmlPath) continue; // handled separately

      if (rel.endsWith(".css")) {
        const fileName = this.fileName(rel);
        theme[`assets/css/${fileName}`] = dirent.content as string;
        if (!firstCss) firstCss = fileName; // Track first CSS file
      } else if (rel.endsWith(".js")) {
        const fileName = this.fileName(rel);
        theme[`assets/js/${fileName}`] = dirent.content as string;
        if (!firstJs) firstJs = fileName; // Track first JS file
      } else if (/(png|jpg|jpeg|gif|svg|webp)$/.test(rel)) {
        theme[`assets/images/${this.fileName(rel)}`] = dirent.content as string;
      }
    }

    // 4. WordPress required files
    theme["style.css"] = this.buildStyleCss(opts, "/* Additional styles moved to assets/css */\n");
    Object.assign(theme, this.buildPhpTemplates(head, body, firstCss, firstJs));

    // simple placeholder screenshot (solid gray).  Users can replace later.
    theme["screenshot.png"] = ""; // left empty for now, keeps WP happy

    return theme;
  }

  private buildStyleCss(opts: WPThemeOptions, additionalCss: string) {
    const header = `/*\nTheme Name: ${opts.themeName}\nAuthor: ${opts.author ?? "Starsky AI"}\nDescription: ${opts.description ?? "Generated by Starsky AI"}\nVersion: ${opts.version ?? "1.0.0"}\n*/\n\n`;
    return header + additionalCss;
  }

  private buildPhpTemplates(head: string, body: string, cssFile?: string, jsFile?: string) {
    const headerPhp = `<!DOCTYPE html>\n<html <?php language_attributes(); ?>>\n<head>\n${head}\n<?php wp_head(); ?>\n</head>\n<body <?php body_class(); ?>>`;

    const footerPhp = `<?php wp_footer(); ?>\n</body>\n</html>`;

    const indexPhp = `<?php get_header(); ?>\n<main>\n${body}\n</main>\n<?php get_footer(); ?>`;

    const functionsPhp = `<?php
function Digimetrix_theme_setup() {
  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', 'Digimetrix_theme_setup');

function Digimetrix_theme_scripts() {
  // Main stylesheet
  wp_enqueue_style('Starsky-style', get_template_directory_uri() . '/assets/css/${cssFile || 'main.css'}', array(), '${Date.now()}');
  // Main script
  wp_enqueue_script('Starsky-script', get_template_directory_uri() . '/assets/js/${jsFile || 'main.js'}', array(), '${Date.now()}', true);
}
add_action('wp_enqueue_scripts', 'Digimetrix_theme_scripts');
?>`;

    return {
      "header.php": headerPhp,
      "footer.php": footerPhp,
      "index.php": indexPhp,
      "functions.php": functionsPhp,
    } as Record<string, string>;
  }

  /** naive splitter – returns raw strings of <head> and <body> */
  private splitHtml(html: string): { head: string; body: string } {
    if (!html) return { head: "", body: "" };
    const headMatch = html.match(/<head[^>]*>([\s\S]*?)<\/head>/i);
    const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
    return {
      head: headMatch ? headMatch[1].trim() : "",
      body: bodyMatch ? bodyMatch[1].trim() : html.trim(), // fallback to full html
    };
  }

  private fileName(path: string) {
    return path.split("/").pop() || path;
  }
}
